apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "topohub.fullname" . }}-dhcp
  labels:
    {{- include "topohub.labels" . | nindent 4 }}
data:
  dhcp-config.tmpl: |
    # this is for dnsmasq configuration
