apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dhcp-config
  labels:
    {{- include "topohub.labels" . | nindent 4 }}
data:
  dhcp-config.tmpl: |
    # this is for dnsmasq configuration
