name: Auto PR CI Test

on:
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run E2E tests
        run: |
            make images
            make e2e